import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { GlobalStyles } from "./global";
const poppins = Poppins({
  style: ["normal"],
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Master Liga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GlobalStyles}>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
